### ISSUE TITLE
is:issue is:open Problem with pip install Shapely from Traja

### ISSUE THREAD

**Issue by Saran-nns** [justinshenk/traja#1]
Hi Justin,

I tried to 

> pip install traja

 in Jupyter notebook environment with python 3.5.2. OS: Win10 64-bit

Seems like Shapely supports 

> pip install

 only for Linux and OSx, so does the Traja..

**Error** :  
```
Collecting shapely (from traja)
  Downloading https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz (225kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\saran\AppData\Local\Temp\pip-install-pk17ofu_\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\saran\AppData\Local\Temp\pip-install-pk17ofu_\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\saran\AppData\Local\conda\conda\envs\tensor\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
```

**Solution found**:

i) Install Shapely and Geos in the conda env using the command: 

`conda install -c ioos shapely= <version>`

ii) Resume 

`pip install traja`

and its done.

**Comment by justinshenk** [comment]
Closing issue.
